baseurl = "https://stefano-garzarella.github.io"
DefaultContentLanguage = "en"
title = "sgarzare's blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "stefano-garzarella-github-io"
googleAnalytics = "UA-146409373-1"

# Get last modified date for content from Git?
enableGitInfo = false

[Params]
  homeTitle = "Virtualization and networking blog"
  subtitle = "Stefano Garzarella"
  mainSections = ["posts", "post"]
  logo = "img/avatar-icon.jpg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2006/01/02"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  gcse = "011433376634952630999:louybk8offk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Stefano Garzarella"
  website = "https://stefano-garzarella.github.io/page/about"
  email = "sgarzare@redhat.com"
  github = "stefano-garzarella"
  gitlab = "sgarzarella"
  bitbucket = "sgarzarella"
  linkedin = "stefanogarzarella"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "posts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4
