baseurl = "https://stefano-garzarella.github.io"
DefaultContentLanguage = "en"
title = "sgarzare's blog"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-146409373-1"

[Params]
  homeTitle = "Virtualization and networking blog"
  subtitle = "Stefano Garzarella"
  logo = "img/avatar-icon.jpg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2006/01/02"
  commit = true
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Stefano Garzarella"
  website = "stefano-garzarella.github.io"
  email = "sgarzare@redhat.com"
  github = "stefano-garzarella"
  gitlab = "sgarzarella"
  bitbucket = "sgarzarella"
  twitter = "sgarzarella"
  linkedin = "stefanogarzarella"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
